server:
  port: 8080
  servlet:
    context-path: /sp

logging:
  level:
    root: DEBUG
    '[org.springframework.web]': INFO
    '[org.springframework.security]': INFO
    '[org.springframework.security.saml]': INFO
    '[org.opensaml.xmlsec]': TRACE

spring:
  security:
    saml2:
      relyingparty:
        registration:
          samlexample:
            entity-id: test-service-provider
            signing:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/public.cer"
          